### PR TITLE
(Partial) attempt to fix the plugin detection issue on MacOS

### PR DESCRIPTION
**Pull request by klayoutmatthias**
Hi Thomas,

this is a *partial* fix for the plugin detection issue on MacOS.

I have updated the plugin locators, so "*.dylib" files will be recognized. I have also updated the build script, so it copies over the plugin .dylib files. KLayout will find the plugins then.

But I don't find how to make these libraries find their proper dependencies. Maybe I have put them into the wrong folders.

The basic issue is: 
* Content/MacOS/lay_plugins/*.dylib depend on KLayout libraries from Framework and (in some cases) depend on libraries from Content/MacOS/db_plugins
* Content/MacOS/db_plugins/*.dylib depend on KLayout libraries

On Linux I have solved this issue with RPATH's, but on MacOS I don't know how to integrate such a solution in the build script. Maybe you can help. If I manually set DYLD_LIBRARY_PATH to contain the db_plugins and Framework folders, the plugins are loaded properly and I can read and write all file formats plus I see all the tools that I have moved into these plugins.

Best regards,

Matthias

### CODE REVIEW

**Comment by thomaslima** [comment]
I have to investigate what's going on but for that I have to build on my mac which I can't do until this weekend... I can tell you that the RPATH in linux has an equivalent on Mac and the function you are looking for is `SetChangeLibIdentificationName` in build4mac_util.py. The build script is quite convoluted now and I hope to one day simplify it. Essentially the idea is simple:

you look at the dependencies of klayout with `otool -L Content/MacOS/klayout`. Then you'll see the dylib it references. By default qmake gives them absolute paths. Hence we use the command `install_name_tool -change old/full/path/of/dylib @executable_path/relative/dir/to/dylib`. Here, @executable_path is going to be the path of `klayout`. So you can keep the new dylibs in the right place, we just got to update the renaming rules so nothing gets left out. Btw `install_name_tool` does not throw an error if you make a mistake, which makes debug a bit worse.

Hope it helps! Thanks for the patch.

**Comment by klayoutmatthias** [comment]
Hi Thomas,

thanks for these hints. I guess I got it right now. I reworked the build script a little to support more than a single destination for dylib's. With this new script, my local installation "build4mac .. -Y" with Homebrew is functional and the stream formats are available as well as the tools. I have not verified DMG production as I assume this is just one additional packaging step, right?

Best regards,

Matthias

**Comment by thomaslima** [comment]
Thank you Matthias. That is correct. I will test soon. Can you allow me to push to this pull request? There's a checkbox on the right for "allow edits from maintainers".

**Comment by thomaslima** [comment]
@klayoutmatthias your fix worked. Thank you! I would like to make a few changes to this pull request after you allow "edits from maintainers", then it can be merged.

Note: maybe a separate issue: I am not able to run ut_runner anymore on mac because it is not importing libraries correctly.

**Comment by klayoutmatthias** [comment]
Hi Thomas,

"allow edits from maintainers" is already on :-(

It's a pull request into your fork, so I think you should be able to merge it there. I think you can then patch the branch and create a pull request into my repo. This time I hope I won't mess up the merge :-)

I'll try to take a look into the ut_runner issue. 

Best regards,

Matthias

**Comment by klayoutmatthias** [comment]
Hi Thomas,

ut_runner needs DYLD_LIBRARY_PATH set in my case, but I think that's not a new behaviour. This is how I'm able to run it from the root folder:

```
TESTSRC=. TESTTMP=testtmp DYLD_LIBRARY_PATH=qt5.build.macos-HighSierra-release:qt5.build.macos-HighSierra-release/db_plugins qt5.build.macos-HighSierra-release/ut_runner
```

Best regards,

Matthias

**Comment by klayoutmatthias** [comment]
Hi Thomas,

there is one more and very important patch. Please see the comments on this commit. 

With this patch, most unit tests pass. Some of the integration tests don't pass (strmrun, klayout_main and the pymod_import tests). This happens basically because DYLD_LIBRARY_PATH is purged by MacOS on a subprocess. Hence it's not possible to resolve library dependencies by just defining DYLD_LIBRARY_PATH on the calling shell. That's quite annoying and apparently there is no simple workaround. The hard way is to set the variable explicitly on the subprocess. For now, that's a limited number of fails and the majority and most important tests pass.

Best regards,

Matthias

**Comment by atait** [comment]
Hi @thomaslima and @klayoutmatthias ,

Thank you for your work on this. I am watching this conversation. So far this is a little beyond me, but I will jump in if there is something I can add.

Regards,
Alex

**Comment by thomaslima** [comment]
Okay I confirm that the ut_runner actually runs now, although I can't run it in travis unfortunately. I'd like to select a newer subset of tests that should be considered critical before releasing a new binary. But that's for later.

Another note: I discovered that "Allow edits from maintainers" only works in one direction. Since your repo is the master and mine is the fork, you can push to mine but I can't push to yours. Whatever, I will merge it and then create another pull request in your repo. Thanks for the help!!!

**Comment by thomaslima** [comment]
Moving discussion to https://github.com/klayoutmatthias/klayout/pull/179. Travis is running in https://travis-ci.org/lightwave-lab/klayout/builds/437650556

**Pull request merged**
