### PR TITLE
Fixed the recent patch: mouse coordinates need to be scaled by device…

### PR DESCRIPTION
**Pull request by klayoutmatthias**
…PixelRatio too.

### CODE REVIEW

**Comment by thomaslima** [comment]
You, sir, work fast. I will test these very soon. Meanwhile, how long you estimate it would take to convert the other instances of QImage to high DPI? I wonder if we should stop at just the canvas for now.

**Comment by thomaslima** [comment]
I am really sorry about this but I will rebase this branch.

**Comment by klayoutmatthias** [comment]
Why sorry? Thanks for the contribution :-)

**Comment by thomaslima** [comment]
I just figured it messes up the history of commits you had already pulled. so now you have to do some cleaning on your own macOS-retina branch, if not deleting it.

**Pull request merged**
